# Generated by Django 4.0.3 on 2022-03-18 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the country', max_length=50)),
                ('code', models.CharField(help_text='alpha2_code', max_length=2)),
                ('code_2', models.CharField(help_text='alpha2_code', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Name of the host', max_length=30)),
                ('port', models.IntegerField(help_text='Port to conenct to', validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(1)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Fligts.country')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the country', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Fligts.country')),
            ],
        ),
    ]
